--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8 (Homebrew)
-- Dumped by pg_dump version 15.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO n8vea;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO n8vea;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO n8vea;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO n8vea;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO n8vea;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO n8vea;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: breed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.breed (
    breed_id integer NOT NULL,
    breed_name character varying(100) NOT NULL,
    links text,
    image_url text
);


ALTER TABLE public.breed OWNER TO postgres;

--
-- Name: breed_breed_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.breed_breed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.breed_breed_id_seq OWNER TO postgres;

--
-- Name: breed_breed_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.breed_breed_id_seq OWNED BY public.breed.breed_id;


--
-- Name: breed_rank; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.breed_rank (
    breed_name character varying(100) NOT NULL,
    rank_2013 integer,
    rank_2014 integer,
    rank_2015 integer,
    rank_2016 integer,
    rank_2017 integer,
    rank_2018 integer,
    rank_2019 integer,
    rank_2020 integer
);


ALTER TABLE public.breed_rank OWNER TO postgres;

--
-- Name: breed_traits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.breed_traits (
    breed_name character varying(100) NOT NULL,
    affectionate_with_family integer,
    good_with_young_children integer,
    good_with_other_dogs integer,
    shedding_level integer,
    coat_grooming_frequency integer,
    drooling_level integer,
    coat_type character varying(100),
    openness_to_strangers integer,
    playfulness_level integer,
    watchdog_protective_nature integer,
    adaptability_level integer,
    trainability_level integer,
    energy_level integer,
    barking_level integer,
    mental_stimulation_needs integer,
    coat_length character varying(100)
);


ALTER TABLE public.breed_traits OWNER TO postgres;

--
-- Name: breeds_breed; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.breeds_breed (
    breed_id integer NOT NULL,
    breed_name character varying(100) NOT NULL,
    links character varying(200),
    image_url character varying(200)
);


ALTER TABLE public.breeds_breed OWNER TO n8vea;

--
-- Name: breeds_breed_breed_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.breeds_breed ALTER COLUMN breed_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.breeds_breed_breed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: breeds_breedrank; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.breeds_breedrank (
    id bigint NOT NULL,
    breed_id integer NOT NULL,
    rank_2013 integer NOT NULL,
    rank_2014 integer NOT NULL,
    rank_2015 integer NOT NULL,
    rank_2016 integer NOT NULL,
    rank_2017 integer NOT NULL,
    rank_2018 integer NOT NULL,
    rank_2019 integer NOT NULL,
    rank_2020 integer NOT NULL
);


ALTER TABLE public.breeds_breedrank OWNER TO n8vea;

--
-- Name: breeds_breedrank_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.breeds_breedrank ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.breeds_breedrank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: breeds_breedtraits; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.breeds_breedtraits (
    id bigint NOT NULL,
    affectionate_with_family integer NOT NULL,
    good_with_young_children integer NOT NULL,
    good_with_other_dogs integer NOT NULL,
    shedding_level integer NOT NULL,
    coat_grooming_frequency integer NOT NULL,
    drooling_level integer NOT NULL,
    coat_type character varying(100) NOT NULL,
    coat_length character varying(100) NOT NULL,
    openness_to_strangers integer NOT NULL,
    playfulness_level integer NOT NULL,
    watchdog_protective_nature integer NOT NULL,
    adaptability_level integer NOT NULL,
    trainability_level integer NOT NULL,
    energy_level integer NOT NULL,
    barking_level integer NOT NULL,
    mental_stimulation_needs integer NOT NULL,
    breed_id integer NOT NULL
);


ALTER TABLE public.breeds_breedtraits OWNER TO n8vea;

--
-- Name: breeds_breedtraits_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.breeds_breedtraits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.breeds_breedtraits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: breeds_traitdescription; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.breeds_traitdescription (
    id bigint NOT NULL,
    trait_id integer NOT NULL,
    trait character varying(100) NOT NULL,
    trait_1 character varying(100) NOT NULL,
    trait_5 character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.breeds_traitdescription OWNER TO n8vea;

--
-- Name: breeds_traitdescription_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.breeds_traitdescription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.breeds_traitdescription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: breeds_userpreference; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.breeds_userpreference (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    username character varying(100) NOT NULL,
    affectionate_with_family integer NOT NULL,
    good_with_young_children integer NOT NULL,
    good_with_other_dogs integer NOT NULL,
    shedding_level integer NOT NULL,
    coat_grooming_frequency integer NOT NULL,
    drooling_level integer NOT NULL,
    coat_type character varying(100) NOT NULL,
    coat_length character varying(100) NOT NULL,
    openness_to_strangers integer NOT NULL,
    playfullness_level integer NOT NULL,
    watchdog_protective_nature integer NOT NULL,
    adaptability_level integer NOT NULL,
    trainability_level integer NOT NULL,
    energy_level integer NOT NULL,
    barking_level integer NOT NULL,
    mental_stimulation integer NOT NULL,
    breed_id_id integer NOT NULL
);


ALTER TABLE public.breeds_userpreference OWNER TO n8vea;

--
-- Name: breeds_userpreference_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.breeds_userpreference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.breeds_userpreference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO n8vea;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO n8vea;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO n8vea;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO n8vea;

--
-- Name: dog_breed_preference_breed; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.dog_breed_preference_breed (
    breed_id integer NOT NULL,
    breed_name character varying(100) NOT NULL,
    links character varying(500) NOT NULL,
    image_url character varying(500) NOT NULL
);


ALTER TABLE public.dog_breed_preference_breed OWNER TO n8vea;

--
-- Name: dog_breed_preference_breed_breed_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.dog_breed_preference_breed ALTER COLUMN breed_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dog_breed_preference_breed_breed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dog_breed_preference_breedrank; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.dog_breed_preference_breedrank (
    id bigint NOT NULL,
    rank_2013 integer NOT NULL,
    rank_2014 integer NOT NULL,
    rank_2015 integer NOT NULL,
    rank_2016 integer NOT NULL,
    rank_2017 integer NOT NULL,
    rank_2018 integer NOT NULL,
    rank_2019 integer NOT NULL,
    rank_2020 integer NOT NULL,
    breed_id integer NOT NULL,
    CONSTRAINT dog_breed_preference_breedrank_rank_2013_check CHECK ((rank_2013 >= 0)),
    CONSTRAINT dog_breed_preference_breedrank_rank_2014_check CHECK ((rank_2014 >= 0)),
    CONSTRAINT dog_breed_preference_breedrank_rank_2015_check CHECK ((rank_2015 >= 0)),
    CONSTRAINT dog_breed_preference_breedrank_rank_2016_check CHECK ((rank_2016 >= 0)),
    CONSTRAINT dog_breed_preference_breedrank_rank_2017_check CHECK ((rank_2017 >= 0)),
    CONSTRAINT dog_breed_preference_breedrank_rank_2018_check CHECK ((rank_2018 >= 0)),
    CONSTRAINT dog_breed_preference_breedrank_rank_2019_check CHECK ((rank_2019 >= 0)),
    CONSTRAINT dog_breed_preference_breedrank_rank_2020_check CHECK ((rank_2020 >= 0))
);


ALTER TABLE public.dog_breed_preference_breedrank OWNER TO n8vea;

--
-- Name: dog_breed_preference_breedrank_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.dog_breed_preference_breedrank ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dog_breed_preference_breedrank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dog_breed_preference_breedtrait; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.dog_breed_preference_breedtrait (
    id bigint NOT NULL,
    affectionate_with_family integer NOT NULL,
    good_with_young_children integer NOT NULL,
    good_with_other_dogs integer NOT NULL,
    shedding_level integer NOT NULL,
    coat_grooming_frequency integer NOT NULL,
    drooling_level integer NOT NULL,
    coat_type character varying(50) NOT NULL,
    coat_length character varying(50) NOT NULL,
    openness_to_strangers integer NOT NULL,
    playfulness_level integer NOT NULL,
    watchdog_protective_nature integer NOT NULL,
    adaptability_level integer NOT NULL,
    trainability_level integer NOT NULL,
    energy_level integer NOT NULL,
    barking_level integer NOT NULL,
    mental_stimulation integer NOT NULL,
    breed_id integer NOT NULL,
    CONSTRAINT dog_breed_preference_br_playfulness_level_e57164cb_check CHECK ((playfulness_level >= 0)),
    CONSTRAINT dog_breed_preference_breedtrai_watchdog_protective_nature_check CHECK ((watchdog_protective_nature >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_adaptability_level_check CHECK ((adaptability_level >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_affectionate_with_family_check CHECK ((affectionate_with_family >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_barking_level_check CHECK ((barking_level >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_coat_grooming_frequency_check CHECK ((coat_grooming_frequency >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_drooling_level_check CHECK ((drooling_level >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_energy_level_check CHECK ((energy_level >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_good_with_other_dogs_check CHECK ((good_with_other_dogs >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_good_with_young_children_check CHECK ((good_with_young_children >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_mental_stimulation_check CHECK ((mental_stimulation >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_openness_to_strangers_check CHECK ((openness_to_strangers >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_shedding_level_check CHECK ((shedding_level >= 0)),
    CONSTRAINT dog_breed_preference_breedtrait_trainability_level_check CHECK ((trainability_level >= 0))
);


ALTER TABLE public.dog_breed_preference_breedtrait OWNER TO n8vea;

--
-- Name: dog_breed_preference_breedtrait_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.dog_breed_preference_breedtrait ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dog_breed_preference_breedtrait_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dog_breed_preference_traitdescription; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.dog_breed_preference_traitdescription (
    trait_id integer NOT NULL,
    trait character varying(100) NOT NULL,
    trait_1 character varying(100) NOT NULL,
    trait_5 character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.dog_breed_preference_traitdescription OWNER TO n8vea;

--
-- Name: dog_breed_preference_traitdescription_trait_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.dog_breed_preference_traitdescription ALTER COLUMN trait_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dog_breed_preference_traitdescription_trait_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dog_breed_preference_userpreference; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.dog_breed_preference_userpreference (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    username character varying(100) NOT NULL,
    breed_id integer,
    trait character varying(100) NOT NULL
);


ALTER TABLE public.dog_breed_preference_userpreference OWNER TO n8vea;

--
-- Name: dog_breed_preference_userpreference_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

ALTER TABLE public.dog_breed_preference_userpreference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dog_breed_preference_userpreference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.food (
    fdc_id integer NOT NULL,
    description text,
    food_category_id integer
);


ALTER TABLE public.food OWNER TO n8vea;

--
-- Name: food_category; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.food_category (
    id integer NOT NULL,
    code integer,
    description text
);


ALTER TABLE public.food_category OWNER TO n8vea;

--
-- Name: food_nutrient; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.food_nutrient (
    id integer NOT NULL,
    fdc_id integer,
    nutrient_id integer,
    amount numeric
);


ALTER TABLE public.food_nutrient OWNER TO n8vea;

--
-- Name: food_nutrient_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

CREATE SEQUENCE public.food_nutrient_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.food_nutrient_id_seq OWNER TO n8vea;

--
-- Name: food_nutrient_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: n8vea
--

ALTER SEQUENCE public.food_nutrient_id_seq OWNED BY public.food_nutrient.id;


--
-- Name: food_portion; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.food_portion (
    id integer NOT NULL,
    fdc_id integer,
    amount numeric,
    measure_unit_id integer,
    gram_weight numeric
);


ALTER TABLE public.food_portion OWNER TO n8vea;

--
-- Name: food_portion_id_seq; Type: SEQUENCE; Schema: public; Owner: n8vea
--

CREATE SEQUENCE public.food_portion_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.food_portion_id_seq OWNER TO n8vea;

--
-- Name: food_portion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: n8vea
--

ALTER SEQUENCE public.food_portion_id_seq OWNED BY public.food_portion.id;


--
-- Name: laptop; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.laptop (
    model integer NOT NULL,
    speed double precision,
    ram integer,
    hd integer,
    screen double precision,
    price integer
);


ALTER TABLE public.laptop OWNER TO n8vea;

--
-- Name: log; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.log (
    username text,
    food_description text NOT NULL,
    amount_of_food numeric NOT NULL,
    "time" text NOT NULL,
    date date NOT NULL,
    fdc_id integer
);


ALTER TABLE public.log OWNER TO n8vea;

--
-- Name: nutrient; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.nutrient (
    nutrient_id integer NOT NULL,
    name text NOT NULL,
    unit_name text NOT NULL,
    nutrient_nbr numeric
);


ALTER TABLE public.nutrient OWNER TO n8vea;

--
-- Name: pc; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.pc (
    model integer NOT NULL,
    speed double precision,
    ram integer,
    hd integer,
    price integer
);


ALTER TABLE public.pc OWNER TO n8vea;

--
-- Name: printer; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.printer (
    model integer NOT NULL,
    color boolean,
    type character varying(20),
    price integer
);


ALTER TABLE public.printer OWNER TO n8vea;

--
-- Name: product; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.product (
    model integer NOT NULL,
    maker character(1),
    type character varying(20)
);


ALTER TABLE public.product OWNER TO n8vea;

--
-- Name: trait_description; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trait_description (
    trait_id integer NOT NULL,
    trait character varying(100),
    trait_1 character varying(100),
    trait_5 character varying(100),
    description text
);


ALTER TABLE public.trait_description OWNER TO postgres;

--
-- Name: trait_description_trait_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.trait_description_trait_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.trait_description_trait_id_seq OWNER TO postgres;

--
-- Name: trait_description_trait_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.trait_description_trait_id_seq OWNED BY public.trait_description.trait_id;


--
-- Name: user_preference; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_preference (
    user_id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    username character varying(100) NOT NULL,
    affectionate_with_family integer,
    good_with_young_children integer,
    good_with_other_dogs integer,
    shedding_level integer,
    coat_grooming_frequency integer,
    drooling_level integer,
    coat_type character varying(100),
    coat_length character varying(100),
    openness_to_strangers integer,
    playfullness_level integer,
    watchdog_protective_nature integer,
    adaptability_level integer,
    trainability_level integer,
    energy_level integer,
    barking_level integer,
    mental_stimulation integer,
    breed_id integer
);


ALTER TABLE public.user_preference OWNER TO postgres;

--
-- Name: user_preference_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_preference_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.user_preference_user_id_seq OWNER TO postgres;

--
-- Name: user_preference_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_preference_user_id_seq OWNED BY public.user_preference.user_id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: n8vea
--

CREATE TABLE public.users (
    username text NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL
);


ALTER TABLE public.users OWNER TO n8vea;

--
-- Name: breed breed_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.breed ALTER COLUMN breed_id SET DEFAULT nextval('public.breed_breed_id_seq'::regclass);


--
-- Name: food_nutrient id; Type: DEFAULT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food_nutrient ALTER COLUMN id SET DEFAULT nextval('public.food_nutrient_id_seq'::regclass);


--
-- Name: food_portion id; Type: DEFAULT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food_portion ALTER COLUMN id SET DEFAULT nextval('public.food_portion_id_seq'::regclass);


--
-- Name: trait_description trait_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trait_description ALTER COLUMN trait_id SET DEFAULT nextval('public.trait_description_trait_id_seq'::regclass);


--
-- Name: user_preference user_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_preference ALTER COLUMN user_id SET DEFAULT nextval('public.user_preference_user_id_seq'::regclass);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: breed breed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.breed
    ADD CONSTRAINT breed_pkey PRIMARY KEY (breed_name);


--
-- Name: breed_rank breed_rank_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.breed_rank
    ADD CONSTRAINT breed_rank_pkey PRIMARY KEY (breed_name);


--
-- Name: breed_traits breed_traits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.breed_traits
    ADD CONSTRAINT breed_traits_pkey PRIMARY KEY (breed_name);


--
-- Name: breeds_breed breeds_breed_breed_name_key; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.breeds_breed
    ADD CONSTRAINT breeds_breed_breed_name_key UNIQUE (breed_name);


--
-- Name: breeds_breed breeds_breed_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.breeds_breed
    ADD CONSTRAINT breeds_breed_pkey PRIMARY KEY (breed_id);


--
-- Name: breeds_breedrank breeds_breedrank_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.breeds_breedrank
    ADD CONSTRAINT breeds_breedrank_pkey PRIMARY KEY (id);


--
-- Name: breeds_breedtraits breeds_breedtraits_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.breeds_breedtraits
    ADD CONSTRAINT breeds_breedtraits_pkey PRIMARY KEY (id);


--
-- Name: breeds_traitdescription breeds_traitdescription_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.breeds_traitdescription
    ADD CONSTRAINT breeds_traitdescription_pkey PRIMARY KEY (id);


--
-- Name: breeds_userpreference breeds_userpreference_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.breeds_userpreference
    ADD CONSTRAINT breeds_userpreference_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: dog_breed_preference_breed dog_breed_preference_breed_breed_name_key; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_breed
    ADD CONSTRAINT dog_breed_preference_breed_breed_name_key UNIQUE (breed_name);


--
-- Name: dog_breed_preference_breed dog_breed_preference_breed_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_breed
    ADD CONSTRAINT dog_breed_preference_breed_pkey PRIMARY KEY (breed_id);


--
-- Name: dog_breed_preference_breedrank dog_breed_preference_breedrank_breed_id_key; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_breedrank
    ADD CONSTRAINT dog_breed_preference_breedrank_breed_id_key UNIQUE (breed_id);


--
-- Name: dog_breed_preference_breedrank dog_breed_preference_breedrank_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_breedrank
    ADD CONSTRAINT dog_breed_preference_breedrank_pkey PRIMARY KEY (id);


--
-- Name: dog_breed_preference_breedtrait dog_breed_preference_breedtrait_breed_name_key; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_breedtrait
    ADD CONSTRAINT dog_breed_preference_breedtrait_breed_name_key UNIQUE (breed_id);


--
-- Name: dog_breed_preference_breedtrait dog_breed_preference_breedtrait_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_breedtrait
    ADD CONSTRAINT dog_breed_preference_breedtrait_pkey PRIMARY KEY (id);


--
-- Name: dog_breed_preference_traitdescription dog_breed_preference_traitdescription_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_traitdescription
    ADD CONSTRAINT dog_breed_preference_traitdescription_pkey PRIMARY KEY (trait_id);


--
-- Name: dog_breed_preference_traitdescription dog_breed_preference_traitdescription_trait_key; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_traitdescription
    ADD CONSTRAINT dog_breed_preference_traitdescription_trait_key UNIQUE (trait);


--
-- Name: dog_breed_preference_userpreference dog_breed_preference_userpreference_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_userpreference
    ADD CONSTRAINT dog_breed_preference_userpreference_pkey PRIMARY KEY (id);


--
-- Name: dog_breed_preference_userpreference dog_breed_preference_userpreference_trait_key; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_userpreference
    ADD CONSTRAINT dog_breed_preference_userpreference_trait_key UNIQUE (trait);


--
-- Name: dog_breed_preference_userpreference dog_breed_preference_userpreference_username_key; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_userpreference
    ADD CONSTRAINT dog_breed_preference_userpreference_username_key UNIQUE (username);


--
-- Name: food_category food_category_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food_category
    ADD CONSTRAINT food_category_pkey PRIMARY KEY (id);


--
-- Name: food_nutrient food_nutrient_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food_nutrient
    ADD CONSTRAINT food_nutrient_pkey PRIMARY KEY (id);


--
-- Name: food food_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT food_pkey PRIMARY KEY (fdc_id);


--
-- Name: food_portion food_portion_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food_portion
    ADD CONSTRAINT food_portion_pkey PRIMARY KEY (id);


--
-- Name: laptop laptop_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.laptop
    ADD CONSTRAINT laptop_pkey PRIMARY KEY (model);


--
-- Name: log log_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.log
    ADD CONSTRAINT log_pkey PRIMARY KEY (food_description, "time", date);


--
-- Name: nutrient nutrient_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.nutrient
    ADD CONSTRAINT nutrient_pkey PRIMARY KEY (nutrient_id);


--
-- Name: pc pc_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.pc
    ADD CONSTRAINT pc_pkey PRIMARY KEY (model);


--
-- Name: printer printer_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.printer
    ADD CONSTRAINT printer_pkey PRIMARY KEY (model);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (model);


--
-- Name: trait_description trait_description_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trait_description
    ADD CONSTRAINT trait_description_pkey PRIMARY KEY (trait_id);


--
-- Name: user_preference user_preference_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_preference
    ADD CONSTRAINT user_preference_pkey PRIMARY KEY (first_name, last_name, username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: breeds_breed_breed_name_b4848e8f_like; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX breeds_breed_breed_name_b4848e8f_like ON public.breeds_breed USING btree (breed_name varchar_pattern_ops);


--
-- Name: breeds_breedrank_breed_id_1c2072d8; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX breeds_breedrank_breed_id_1c2072d8 ON public.breeds_breedrank USING btree (breed_id);


--
-- Name: breeds_breedtraits_breed_id_0e75e21a; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX breeds_breedtraits_breed_id_0e75e21a ON public.breeds_breedtraits USING btree (breed_id);


--
-- Name: breeds_userpreference_breed_id_id_b786e95c; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX breeds_userpreference_breed_id_id_b786e95c ON public.breeds_userpreference USING btree (breed_id_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: dog_breed_preference_breed_breed_name_57674528_like; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX dog_breed_preference_breed_breed_name_57674528_like ON public.dog_breed_preference_breed USING btree (breed_name varchar_pattern_ops);


--
-- Name: dog_breed_preference_traitdescription_trait_91b0e60a_like; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX dog_breed_preference_traitdescription_trait_91b0e60a_like ON public.dog_breed_preference_traitdescription USING btree (trait varchar_pattern_ops);


--
-- Name: dog_breed_preference_userpreference_breed_id_3e82bf45; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX dog_breed_preference_userpreference_breed_id_3e82bf45 ON public.dog_breed_preference_userpreference USING btree (breed_id);


--
-- Name: dog_breed_preference_userpreference_trait_2ae85884_like; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX dog_breed_preference_userpreference_trait_2ae85884_like ON public.dog_breed_preference_userpreference USING btree (trait varchar_pattern_ops);


--
-- Name: dog_breed_preference_userpreference_username_53f4a020_like; Type: INDEX; Schema: public; Owner: n8vea
--

CREATE INDEX dog_breed_preference_userpreference_username_53f4a020_like ON public.dog_breed_preference_userpreference USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: breed_rank breed_rank_breed_name_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.breed_rank
    ADD CONSTRAINT breed_rank_breed_name_fkey FOREIGN KEY (breed_name) REFERENCES public.breed(breed_name);


--
-- Name: breed_traits breed_traits_breed_name_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.breed_traits
    ADD CONSTRAINT breed_traits_breed_name_fkey FOREIGN KEY (breed_name) REFERENCES public.breed(breed_name);


--
-- Name: breeds_breedrank breeds_breedrank_breed_id_1c2072d8_fk_breeds_breed_breed_id; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.breeds_breedrank
    ADD CONSTRAINT breeds_breedrank_breed_id_1c2072d8_fk_breeds_breed_breed_id FOREIGN KEY (breed_id) REFERENCES public.breeds_breed(breed_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: breeds_breedtraits breeds_breedtraits_breed_id_0e75e21a_fk_breeds_breed_breed_id; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.breeds_breedtraits
    ADD CONSTRAINT breeds_breedtraits_breed_id_0e75e21a_fk_breeds_breed_breed_id FOREIGN KEY (breed_id) REFERENCES public.breeds_breed(breed_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: breeds_userpreference breeds_userpreferenc_breed_id_id_b786e95c_fk_breeds_br; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.breeds_userpreference
    ADD CONSTRAINT breeds_userpreferenc_breed_id_id_b786e95c_fk_breeds_br FOREIGN KEY (breed_id_id) REFERENCES public.breeds_breed(breed_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dog_breed_preference_breedrank dog_breed_preference_breed_id_36f17d0c_fk_dog_breed; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_breedrank
    ADD CONSTRAINT dog_breed_preference_breed_id_36f17d0c_fk_dog_breed FOREIGN KEY (breed_id) REFERENCES public.dog_breed_preference_breed(breed_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dog_breed_preference_userpreference dog_breed_preference_breed_id_3e82bf45_fk_dog_breed; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_userpreference
    ADD CONSTRAINT dog_breed_preference_breed_id_3e82bf45_fk_dog_breed FOREIGN KEY (breed_id) REFERENCES public.dog_breed_preference_breed(breed_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dog_breed_preference_breedtrait dog_breed_preference_breed_id_d4e9bef0_fk_dog_breed; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_breedtrait
    ADD CONSTRAINT dog_breed_preference_breed_id_d4e9bef0_fk_dog_breed FOREIGN KEY (breed_id) REFERENCES public.dog_breed_preference_breed(breed_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dog_breed_preference_userpreference dog_breed_preference_trait_2ae85884_fk_dog_breed; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.dog_breed_preference_userpreference
    ADD CONSTRAINT dog_breed_preference_trait_2ae85884_fk_dog_breed FOREIGN KEY (trait) REFERENCES public.dog_breed_preference_traitdescription(trait) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: food food_food_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT food_food_category_id_fkey FOREIGN KEY (food_category_id) REFERENCES public.food_category(id);


--
-- Name: food_nutrient food_nutrient_fdc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food_nutrient
    ADD CONSTRAINT food_nutrient_fdc_id_fkey FOREIGN KEY (fdc_id) REFERENCES public.food(fdc_id);


--
-- Name: food_nutrient food_nutrient_nutrient_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food_nutrient
    ADD CONSTRAINT food_nutrient_nutrient_id_fkey FOREIGN KEY (nutrient_id) REFERENCES public.nutrient(nutrient_id);


--
-- Name: food_portion food_portion_fdc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.food_portion
    ADD CONSTRAINT food_portion_fdc_id_fkey FOREIGN KEY (fdc_id) REFERENCES public.food(fdc_id);


--
-- Name: log log_fdc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.log
    ADD CONSTRAINT log_fdc_id_fkey FOREIGN KEY (fdc_id) REFERENCES public.food(fdc_id);


--
-- Name: log log_username_fkey; Type: FK CONSTRAINT; Schema: public; Owner: n8vea
--

ALTER TABLE ONLY public.log
    ADD CONSTRAINT log_username_fkey FOREIGN KEY (username) REFERENCES public.users(username);


--
-- PostgreSQL database dump complete
--

