# Generated by Django 4.2.17 on 2024-12-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_breed_preference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedrank',
            old_name='breed_name',
            new_name='breed_id',
        ),
    ]
