name: Django CI

on:
  push:
    branches: [ "fixed2" ]
  pull_request:
    branches: [ "fixed2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r FinalProject/requirements.txt

    - name: Run Tests
      run: |
        python manage.py test
